spring.application.name=Money Vault

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
#spring.datasource.username=vaultapp_user
#spring.datasource.password=Grafton1
spring.datasource.url=jdbc:mysql://localhost:3306/vaultapp
spring.datasource.username=root
spring.datasource.password=Grafton1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
logging.level.root=DEBUG
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
